# Generated by Django 3.2 on 2021-04-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
